"""Skills taxonomy + aliases used to extract skills from resume text.

Canonical name -> list of aliases (all matched case-insensitively, word-boundary).
This is intentionally data-driven so it's easy to extend for any job domain.
"""

SKILL_ALIASES: dict[str, list[str]] = {
    # ── Languages ──
    "JavaScript": ["javascript", "js", "es6", "ecmascript"],
    "TypeScript": ["typescript", "ts"],
    "Python": ["python", "py"],
    "Java": ["java"],
    "C++": ["c++", "cpp"],
    "C#": ["c#", "c sharp", "csharp"],
    "PHP": ["php"],
    "Ruby": ["ruby"],
    "Go": ["golang", "go lang"],
    "Rust": ["rust"],
    "Kotlin": ["kotlin"],
    "Swift": ["swift"],
    "SQL": ["sql"],
    "HTML": ["html", "html5"],
    "CSS": ["css", "css3"],
    # ── Frontend ──
    "React": ["react", "reactjs", "react.js"],
    "Next.js": ["next.js", "nextjs", "next js"],
    "Vue": ["vue", "vuejs", "vue.js"],
    "Angular": ["angular", "angularjs"],
    "Svelte": ["svelte", "sveltekit"],
    "Redux": ["redux"],
    "Tailwind CSS": ["tailwind", "tailwindcss", "tailwind css"],
    "Bootstrap": ["bootstrap"],
    "SASS": ["sass", "scss"],
    # ── Backend ──
    "Node.js": ["node.js", "nodejs", "node js", "node"],
    "Express": ["express", "expressjs", "express.js"],
    "Django": ["django"],
    "Flask": ["flask"],
    "FastAPI": ["fastapi", "fast api"],
    "Spring": ["spring", "spring boot", "springboot"],
    "Laravel": ["laravel"],
    "GraphQL": ["graphql"],
    "REST APIs": ["rest", "rest api", "rest apis", "restful"],
    # ── Databases ──
    "MongoDB": ["mongodb", "mongo"],
    "PostgreSQL": ["postgresql", "postgres"],
    "MySQL": ["mysql"],
    "Redis": ["redis"],
    "SQLite": ["sqlite"],
    "Firebase": ["firebase"],
    # ── DevOps / Cloud ──
    "Docker": ["docker"],
    "Kubernetes": ["kubernetes", "k8s"],
    "AWS": ["aws", "amazon web services"],
    "Azure": ["azure"],
    "GCP": ["gcp", "google cloud"],
    "CI/CD": ["ci/cd", "cicd", "ci cd", "continuous integration"],
    "Terraform": ["terraform"],
    "Linux": ["linux", "unix"],
    "Git": ["git", "github", "gitlab", "version control"],
    "Nginx": ["nginx"],
    # ── Data / AI ──
    "Machine Learning": ["machine learning", "ml"],
    "Deep Learning": ["deep learning"],
    "TensorFlow": ["tensorflow"],
    "PyTorch": ["pytorch"],
    "Pandas": ["pandas"],
    "NumPy": ["numpy"],
    "scikit-learn": ["scikit-learn", "sklearn", "scikit learn"],
    "Power BI": ["power bi", "powerbi"],
    "Excel": ["excel", "microsoft excel"],
    "Statistics": ["statistics", "statistical analysis"],
    # ── Design ──
    "Figma": ["figma"],
    "Adobe XD": ["adobe xd", "xd"],
    "Photoshop": ["photoshop"],
    "Prototyping": ["prototyping", "prototype"],
    "Wireframing": ["wireframing", "wireframe"],
    "Design Systems": ["design system", "design systems"],
    "User Research": ["user research", "ux research"],
    # ── QA ──
    "Selenium": ["selenium"],
    "Cypress": ["cypress"],
    "Jest": ["jest"],
    "Playwright": ["playwright"],
    "Manual Testing": ["manual testing", "manual tester", "test execution"],
    "Automation Testing": ["automation testing", "test automation", "automated testing"],
    "API Testing": ["api testing", "postman", "rest assured"],
    "Performance Testing": ["performance testing", "load testing", "jmeter"],
    "Test Case Design": ["test case", "test cases", "test plan", "test scenarios"],
    "Regression Testing": ["regression testing", "regression suite"],
    "Bug Tracking": ["bug tracking", "jira", "bugzilla", "defect tracking"],
    # ── Mobile ──
    "Flutter": ["flutter", "dart"],
    "React Native": ["react native", "react-native"],
    "Android": ["android", "android studio", "jetpack compose"],
    "iOS": ["ios", "xcode", "swiftui"],
    # ── IT support / systems ──
    "Technical Support": [
        "technical support", "tech support", "it support", "desktop support",
        "support engineer", "support specialist",
    ],
    "Helpdesk": ["helpdesk", "help desk", "service desk", "ticketing", "servicenow"],
    "Troubleshooting": ["troubleshooting", "troubleshoot", "fault finding", "diagnostics"],
    "Hardware Repair": ["hardware repair", "hardware troubleshooting", "pc repair", "assembling"],
    "Windows Server": ["windows server", "server 2016", "server 2019", "server 2022"],
    "Active Directory": ["active directory", "ad ds", "group policy", "gpo"],
    "Office 365": ["office 365", "o365", "microsoft 365", "m365", "exchange online"],
    "Virtualization": ["virtualization", "vmware", "hyper-v", "hyperv", "esxi", "virtualbox"],
    "Backup & Recovery": ["backup", "disaster recovery", "veeam", "restore"],
    "Remote Support": ["remote desktop", "rdp", "teamviewer", "anydesk", "remote support"],
    # ── Networking ──
    "TCP/IP": ["tcp/ip", "tcpip", "tcp ip"],
    "Routing & Switching": ["routing", "switching", "routers", "switches", "ospf", "bgp", "vlan"],
    "Cisco": ["cisco", "ccna", "ccnp", "ios-xe"],
    "Firewalls": ["firewall", "firewalls", "fortigate", "palo alto", "sophos", "pfsense"],
    "VPN": ["vpn", "ipsec", "openvpn"],
    "DNS": ["dns", "dhcp", "bind9"],
    "Wireless Networks": ["wireless", "wi-fi", "wifi", "wlan", "access point"],
    "Network Troubleshooting": ["network troubleshooting", "packet capture", "wireshark", "ping", "traceroute"],
    # ── Security ──
    "Network Security": ["network security", "cyber security", "cybersecurity", "infosec"],
    "Penetration Testing": ["penetration testing", "pen testing", "pentest", "ethical hacking", "burp suite", "metasploit"],
    "Vulnerability Assessment": ["vulnerability assessment", "vulnerability scanning", "nessus", "openvas"],
    "SIEM": ["siem", "splunk", "qradar", "wazuh"],
    "Incident Response": ["incident response", "soc analyst", "threat hunting"],
    "Compliance": ["iso 27001", "iso27001", "gdpr", "compliance", "pci dss"],
    # ── Databases / admin ──
    "Oracle": ["oracle", "pl/sql", "plsql"],
    "SQL Server": ["sql server", "mssql", "t-sql", "tsql"],
    "Database Administration": ["database administration", "dba", "database admin"],
    "Query Optimization": ["query optimization", "query tuning", "indexing", "execution plan"],
    "ETL": ["etl", "data pipeline", "data pipelines", "ssis", "airflow"],
    "Data Visualization": ["data visualization", "dashboards", "tableau", "looker"],
    "NLP": ["nlp", "natural language processing", "spacy", "transformers"],
    "Computer Vision": ["computer vision", "opencv", "image processing"],
    "LLMs": ["llm", "llms", "prompt engineering", "gpt", "langchain", "rag"],
    # ── Management / business ──
    "Project Management": ["project management", "project manager", "pmp", "prince2"],
    "Business Analysis": ["business analysis", "business analyst", "requirement gathering", "brd", "srs"],
    "Stakeholder Management": ["stakeholder management", "client management", "client communication"],
    "Documentation": ["documentation", "technical writing", "sop", "runbook"],
    "Risk Management": ["risk management", "risk assessment"],
    # ── Marketing / operations ──
    "Digital Marketing": ["digital marketing", "google ads", "ppc", "campaign management"],
    "SEO": ["seo", "search engine optimization", "on-page", "off-page"],
    "Social Media Marketing": ["social media marketing", "smm", "meta ads", "facebook ads"],
    "Content Writing": ["content writing", "copywriting", "content creation", "blog writing"],
    "Google Analytics": ["google analytics", "ga4"],
    "Sales": ["sales", "lead generation", "business development", "crm", "salesforce"],
    "Recruitment": ["recruitment", "recruiting", "talent acquisition", "sourcing", "hiring"],
    "HR Operations": ["hr operations", "payroll", "employee relations", "onboarding"],
    "Accounting": ["accounting", "bookkeeping", "quickbooks", "ledger", "invoicing"],
    "Data Entry": ["data entry", "data encoding"],
    "MS Office": ["ms office", "microsoft office", "ms word", "powerpoint"],
    "Customer Handling": ["customer service", "customer support", "customer handling", "client handling"],
    "Video Editing": ["video editing", "premiere pro", "after effects", "final cut"],
    "Illustrator": ["illustrator", "adobe illustrator"],
    "Canva": ["canva"],
    "Accessibility": ["accessibility", "wcag", "a11y"],
    # ── Fundamentals ──
    "Data Structures & Algorithms": ["data structures", "algorithms", "dsa"],
    "OOP": ["oop", "object oriented", "object-oriented"],
    "System Design": ["system design", "high level design", "scalability"],
    "Design Patterns": ["design patterns", "solid principles"],
    "Bash": ["bash", "shell scripting", "powershell", "shell script"],
    "Monitoring": ["monitoring", "prometheus", "grafana", "nagios", "zabbix", "logging"],
    "Ansible": ["ansible"],
    "Jenkins": ["jenkins"],
    "GitHub Actions": ["github actions", "gitlab ci"],
    # ── Soft skills ──
    "Communication": ["communication", "communicator"],
    "Teamwork": ["teamwork", "team player", "collaboration"],
    "Leadership": ["leadership", "team lead", "led a team"],
    "Problem Solving": ["problem solving", "problem-solving"],
    "Agile": ["agile", "scrum", "kanban"],
    "Time Management": ["time management", "prioritization"],
    "Adaptability": ["adaptability", "adaptable", "flexible"],
    "Critical Thinking": ["critical thinking", "analytical thinking", "analytical skills"],
    "Attention to Detail": ["attention to detail", "detail oriented", "detail-oriented"],
    "Training & Development": ["training", "mentoring", "coaching"],
}
